namespace GuildWarsInterface.Declarations
{
        public enum Attribute
        {
                FastCasting = 0,
                IllusionMagic = 1,
                DominationMagic = 2,
                InspirationMagic = 3,
                BloodMagic = 4,
                DeathMagic = 5,
                SoulReaping = 6,
                Curses = 7,
                AirMagic = 8,
                EarthMagic = 9,
                FireMagic = 10,
                WaterMagic = 11,
                EnergyStorage = 12,
                HealingPrayers = 13,
                SmitingPrayers = 14,
                ProtectionPrayers = 15,
                DivineFavor = 16,
                Strength = 17,
                AxeMastery = 18,
                HammerMastery = 19,
                Swordsmanship = 20,
                Tactics = 21,
                BeastMastery = 22,
                Expertise = 23,
                WildernessSurvival = 24,
                Marksmanship = 25,
                Unused1 = 26,
                Unused2 = 27,
                Unused3 = 28,
                DaggerMastery = 29,
                DeadlyArts = 30,
                ShadowArts = 31,
                Communing = 32,
                RestorationMagic = 33,
                ChannelingMagic = 34,
                CriticalStrikes = 35,
                SpawningPower = 36,
                SpearMastery = 37,
                Command = 38,
                Motivation = 39,
                Leadership = 40,
                ScytheMastery = 41,
                WindPrayers = 42,
                EarthPrayers = 43,
                Mysticism = 44,
                Unused4
        }
}